apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-nodejs.fullname" . }}
  labels:
    {{- include "sample-nodejs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "sample-nodejs.port" . }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sample-nodejs.selectorLabels" . | nindent 4 }}
