apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nodejs
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/simzacks/sample-nodejs.git
    targetRevision: main
    path: gitops/workloads/nodejs
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
